version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.7
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - pip install -r requirements.txt
      - pre-commit run --all-files

      - mvn clean install --no-transfer-progress
